// auth.js
export const LOGOUT = "LOGOUT";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const UPDATE_USER = "UPDATE_USER";
export const DEFAULT_AUTH_STATE = "DEFAULT_TOP_PROJECTS_STATE";

// lang.js
export const SET_LOCALE = "SET_LOCALE";

// projects.js
export const RETRIEVE_PROJECTS = "RETRIEVE_PROJECTS";
export const RETRIEVE_PROJECT = "RETRIEVE_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECTS_FILTER = "UPDATE_PROJECTS_FILTER";
export const UPDATE_USER_FILTER = "UPDATE_USER_FILTER";
export const UPDATE_KEYWORDS = "UPDATE_KEYWORDS";
export const UPDATE_SHOW = "UPDATE_SHOW";
export const DEFAULT_SHOW = "DEFAULT_SHOW";
export const UPDATE_DATE_FILTER = "UPDATE_DATE_FILTER";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DEFAULT_PROJECTS_STATE = "DEFAULT_PROJECTS_STATE";

// categories.js
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const DEFAULT_CATEGORIES_STATE = "DEFAULT_CATEGORIES_STATE";

// likes.js
export const RETRIEVE_LIKES = "RETRIEVE_LIKES";
export const CREATE_LIKE = "CREATE_LIKE";
export const DELETE_LIKE = "DELETE_LIKE";
export const DEFAULT_LIKES_STATE = "DEFAULT_LIKES_STATE";

// users.js
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const DEFAULT_USERS_STATE = "DEFAULT_USERS_STATE";

// games.js
export const RETRIEVE_GAMES = "RETRIEVE_GAMES";
export const RETRIEVE_PLAYERS = "RETRIEVE_PLAYERS";
export const UPDATE_GAMES_FILTER = "UPDATE_GAMES_FILTER";
export const DEFAULT_GAMES_STATE = "DEFAULT_GAMES_STATE";
export const DEFAULT_PLAYERS = "DEFAULT_PLAYERS";

// ranking.js
export const RETRIEVE_TOP_PROJECTS = "RETRIEVE_TOP_PROJECTS";
export const UPDATE_RANKING_FILTER = "UPDATE_RANKING_FILTER";
export const UPDATE_TOP_PROJECT = "UPDATE_TOP_PROJECT";
export const DEFAULT_TOP_PROJECTS_STATE = "DEFAULT_TOP_PROJECTS_STATE";
